name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        meteor: [3.0.1]

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          curl https://install.meteor.com | /bin/sh

      - name: Setup tests
        run: |
          meteor create --release ${{ matrix.meteor }} --bare test
          cd test
          meteor npm i --save puppeteer chai

      - name: Test
        working-directory: ./test
        run: METEOR_PACKAGE_DIRS="../" TEST_BROWSER_DRIVER=puppeteer meteor test-packages --once --driver-package meteortesting:mocha ../
